ALTER TABLE articles
  MODIFY published_at TIMESTAMP(3) NOT NULL,
  MODIFY created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  MODIFY updated_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
